-- 코드를 입력하세요
# SELECT AO.ANIMAL_ID, AO.NAME
# FROM ANIMAL_OUTS AS AO
# LEFT OUTER JOIN
# (SELECT ANIMAL_ID, NAME FROM ANIMAL_INS) AS AI
# ON AO.ANIMAL_ID = AI.ANIMAL_ID
# WHERE AI.NAME IS NULL
# ORDER BY AO.ANIMAL_ID; 
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS);