-- 코드를 입력하세요
WITH RECURSIVE TEMP(num) AS (
  SELECT 0
  UNION ALL
  SELECT num + 1 FROM TEMP WHERE num < 23
)
SELECT T.NUM,
COUNT(DATETIME) AS COUNT
FROM TEMP T
LEFT OUTER JOIN
ANIMAL_OUTS AO
ON T.NUM = HOUR(AO.DATETIME)
GROUP BY T.NUM
ORDER BY T.NUM;